service: ${opt:service-name, 'csv-protobuf-pipeline'}

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.6
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

package:
  exclude:
    - ./*
    - ./pandas-layer/**
    - ./node_modules/**

custom:
  buckets:
    input: 
      name: ${opt:input, '${self:service}-${self:provider.stage}-input'}
    output:
      name: ${opt:output, '${self:service}-${self:provider.stage}-output'}
      prefix: ${opt:output-prefix, ''}

  scipy:
    us-west-2:
      arn: arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python36-SciPy1x:2

layers:
  pandas:
    path: pandas-layer
    name: ${self:service}-${self:provider.stage}-pandas
    description: Python's pandas library and dependencies
    compatibleRuntimes:
      - ${self:provider.runtime}
    allowedAccounts:
      - '*'

functions:
  convert:
    handler: functions/convert.toProto
    layers:
      - ${self:custom.scipy.${self:provider.region}.arn}
      - Ref: PandasLambdaLayer
    events:
      - s3: ${self:custom.buckets.input.name}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:*
          - s3:DeleteObject
        Resource:
          - arn:aws:s3:::${self:custom.buckets.input.name}
          - arn:aws:s3:::${self:custom.buckets.input.name}/*
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - arn:aws:s3:::${self:custom.buckets.output.name}/*
    environment:
      train_data_bucket: ${self:custom.buckets.output.name}
      train_data_prefix: ${self:custom.buckets.output.prefix}
